### ISSUE TITLE
GPU not recognized

### ISSUE THREAD

**Issue by ChFunke** [bethgelab/docker#1]
I tried to use the docker container bethgelab/jupyter-deeplearning (version: cuda6.5) on cantor. I used the commands:
docker pull bethgelab/jupyter-deeplearning:cuda6.5
GPU=0 ./agmb-docker run -d bethgelab/jupyter-deeplearning:cuda6.5

The build was successful, but the GPUs aren't recognized: The command nvidia-smi results in the following error message:
Unable to determine the device handle for GPU 0000:03:00.0: Unknown Error

Best Christina

**Comment by jonasrauber** [comment]
is this still relevant?

**Comment by ChFunke** [comment]
It's still not working. But at the moment, I don't need the docker containers.

**Comment by aecker** [comment]
I'm closing this, since cantor will be upgraded to GTX 1080s soon.
