### ISSUE TITLE
CPU only version not working

### ISSUE THREAD

**Issue by leongatys** [bethgelab/docker#3]
Pulling bethgelab/jupyter-deeplearning:ubuntu-14.04 onto my laptop without cuda devices and then running 
./agmb-docker run -e GROUPS=sudo -e USER_HOME=$HOME -p 534:8888 -d bethgelab/jupyter-deeplearning:ubuntu-14.04
gives error
[ NVIDIA ] =ERROR= Command not found: nvidia-smi

When just running 
docker run -d -p 534:8888 bethgelab/jupyter-deeplearning:ubuntu-14.04
the container immediately stops as if no notebook is started

**Comment by jonasrauber** [comment]
I think a simply script like agmb-docker but without all the nvidia and gpu stuff (i.e. a script that just sets the environment variables USER, USER_ID, USER_ENCRYPTED_PASSWORD, …) should solve this. Of course, making this part of the agmb-docker script would be nice. /cc @wielandbrendel

**Comment by wielandbrendel** [comment]
Works perfectly fine for me. @leongatys Are you sure you are using the latest agmb-docker script?

**Comment by aecker** [comment]
Has this been resolved @leongatys ?

**Comment by leongatys** [comment]
I don't know, I haven't tried this with the latest version, but back then I found some way around it.

**Comment by jonasrauber** [comment]
The new agmb-docker script calls nvidia-docker, which will not be available, so it certainly won't work out of the box. Maybe it's enough to overwrite to call agmb-docker with the DOCKER variable set to docker, but I guess one would also need to specify several USER_\* variables. In the end, I don't think the agmb-docker script is intended to be used for these cases.

**Comment by aecker** [comment]
Makes sense. Closing as wontfix.
