### ISSUE TITLE
nvidia-smi not available via ssh

### ISSUE THREAD

**Issue by matthias-k** [bethgelab/docker#5]
When I start a contanier with `GPU=0,1,2,3 ./agmb-docker run -d bethgelab/jupyter-deeplearning:cuda7.5-cudnn4` and then ssh into it, I can't use nvidia-smi:

```
mkuemmerer@2bf98ac6fa67:~$ nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```

When I start the shell via `docker exec -it container_name bash`, `nvidia-smi` works, even after I change the user to my own via `su mkuemmerer`.

**Comment by aecker** [comment]
I had the same problem for a while, but it's fixed now.
